FishhawkLake/FishhawkLake/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using FishhawkLake.CustomFilters;
using FishhawkLake.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace FishhawkLake.Controllers
{
    [AuthLogAttribute(Roles = "Admin")]
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }



        /// <summary>
        /// Get All Roles
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        /// <summary>
        /// Create  a New role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary>
        /// Create a New Role
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            try { 
                context.Roles.Add(Role);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErrorPartial", "Error");
            }
        }


    }
}

FishhawkLake/FishhawkLake/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

    <h2>Create</h2>

    <style type="text/css">
        #tbrole, .c {
            border: double;
        }
    </style>


    @using (Html.BeginForm())
    {
        <table id="tbrole">
            <tr>
                <td class="c">Enter Role Name To be Created:</td>
                <td class="c">
                    @Html.EditorFor(m => m.Name)
                </td>
            </tr>
        </table>
        <input type="submit" value="Create Role" />
    }
}

FishhawkLake/FishhawkLake/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2>

@Html.ActionLink("Create Role", "Create", "Role")

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

<table id="tbrole">
    <tr>
        <td class="c">
            Role Name
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Add New User", "AddUser", "Account")